/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Nunito Sans"', 'sans-serif'],
      },
      colors: {
        primary: '#835400',
        background: '#faf8ff',
        'on-error-container': '#93000a',
        'error-container': '#ffdad6',
        'secondary-fixed': '#cae6ff',
        'on-surface-variant': '#534433',
        'on-secondary-fixed': '#001e30',
        'on-primary': '#ffffff',
        'on-secondary-container': '#004465',
        'surface-container-low': '#f2f3ff',
        'on-primary-fixed': '#2a1800',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#ffa800',
        'on-tertiary-fixed': '#00210c',
        'secondary-container': '#36b5fd',
        'surface-container-highest': '#dbe1ff',
        'surface-container-high': '#e3e7ff',
        'on-secondary-fixed-variant': '#004b70',
        'surface-tint': '#835400',
        'surface-bright': '#faf8ff',
        'on-tertiary-fixed-variant': '#005228',
        'surface-dim': '#d1d9fa',
        'on-primary-fixed-variant': '#643f00',
        'outline-variant': '#d8c3ac',
        outline: '#857460',
        'inverse-on-surface': '#eff0ff',
        'surface-variant': '#dbe1ff',
        'on-background': '#121a33',
        tertiary: '#006d37',
        secondary: '#006493',
        'tertiary-fixed': '#6bfe9c',
        'on-primary-container': '#684200',
        'inverse-surface': '#272f49',
        'on-tertiary': '#ffffff',
        'surface-container': '#ebedff',
        error: '#ba1a1a',
        'on-tertiary-container': '#00562a',
        'tertiary-container': '#3ad478',
        'on-error': '#ffffff',
        'on-secondary': '#ffffff',
        'secondary-fixed-dim': '#8ccdff',
        'on-surface': '#121a33',
        'primary-fixed-dim': '#ffb956',
        surface: '#faf8ff',
        'inverse-primary': '#ffb956',
        'primary-fixed': '#ffddb5',
        'tertiary-fixed-dim': '#4ae183',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '2.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
